// <auto-generated />
using BlazorAI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorAI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260726174417_Add_Persons_Table")]
    partial class Add_Persons_Table
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("BlazorAI.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Salary")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "felipe.gavilan@example.com",
                            IsActive = true,
                            Name = "Felipe Gavilán",
                            Salary = 45000m
                        },
                        new
                        {
                            Id = 2,
                            Email = "maria.lopez@example.com",
                            IsActive = true,
                            Name = "María López",
                            Salary = 52000m
                        },
                        new
                        {
                            Id = 3,
                            Email = "carlos.rodriguez@example.com",
                            IsActive = false,
                            Name = "Carlos Rodríguez",
                            Salary = 61000m
                        },
                        new
                        {
                            Id = 4,
                            Email = "ana.martinez@example.com",
                            IsActive = false,
                            Name = "Ana Martínez",
                            Salary = 48000m
                        },
                        new
                        {
                            Id = 5,
                            Email = "luis.gomez@example.com",
                            IsActive = true,
                            Name = "Luis Gómez",
                            Salary = 55000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
